[project]
name = "fastapib"
version = "0.1.0"
description = "Study fastapi"
authors = [
    {name = "Damian",email = "damian05@inbox.ru"}
]
license = "MIT"
requires-python = ">=3.14, <4.0"
dependencies = [
    "fastapi (==0.141.1)",
    "uvicorn (==0.53.0)",
    "bcrypt (==5.0.0)",
    "python-jose (==3.5.0)",
    "sqlalchemy (>=2.0.54,<3.0.0)",
    "psycopg2-binary (>=2.9.13,<3.0.0)",
    "strawberry-graphql[debug-server] (>=0.327.7,<0.328.0)",
    "secretstorage (>=3.5.0,<4.0.0)",
    "python-multipart (>=0.0.32,<0.0.33)",
    "alembic (>=1.20.0,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "asyncpg (>=0.31.0,<0.32.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
